version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - ./shared:/shared
    networks:
      - tumburu

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run build && npx serve -s dist
    env_file:
      - .env
    volumes:
      - ./shared:/shared
    networks:
      - tumburu

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - tumburu

networks:
  tumburu:
    driver: bridge
