version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - ./shared:/shared
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    networks:
      - tumburu

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./shared:/shared
    env_file:
      - .env
    ports:
      - "5173:5173"
    networks:
      - tumburu

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.prod.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - tumburu

networks:
  tumburu:
    driver: bridge
